### ISSUE TITLE
Lack of primary color

### ISSUE THREAD

**Issue by heokhe** [ThemerBot/ThemerBot#2]
Themes normally have a **primary** color (blue in default Telegram theme) used for toolbars, controls, etc.

Themes generated by the bot are kinda boring (see this [screenshot](https://user-images.githubusercontent.com/24871883/59251162-601ec100-8c3e-11e9-97de-982f82fca103.png)) because there is no primary color.

I copied the theme used in the screenshot and added a primary color to it:
![image](https://user-images.githubusercontent.com/24871883/59251879-1636da80-8c40-11e9-8e09-5c14fda74b90.png)

**Comment by vrumger** [comment]
@Hkh12 The Telegram X theme needs a new template. If you'd like, you can create a new template and open a pull request.

P.S. The image in the first screenshot is nice.

**Comment by heokhe** [comment]
Yes, I've discovered many problems with the template and they must get fixed. I'll try to fix them in upcoming days. 
I also tested the same color in the Official app. Result was better but I think **it still needs a primary color.**

**Comment by YouTwitFace** [comment]
@YouTwitFace Feel free to add that to the pr too. :)

**Comment by vrumger** [comment]
Feel free to add that to the pr too. :)

**Comment by heokhe** [comment]
Now I'm facing a problem.
I have to run the bot using a socks proxy. I followed the instructions on [here](https://github.com/telegraf/telegraf/issues/63). It's OK now but I get a `Error: connect ECONNREFUSED 10.10.34.35:443` when trying to upload files and photos. 

What should I do now? :confused:

**Comment by vrumger** [comment]
Do you have a remote server (maybe a different country) that you're able to use to run the bot? Not sure how much I can help with this situation...

**Comment by heokhe** [comment]
Nope, I don't have any. And it seems like Telegraf.js has removed the support for `apiRoot` and this means I cannot run the bot. :expressionless:

I've made some changes to the template in #3 but they're not tested...

**Comment by vrumger** [comment]
I'll check it out!

**Comment by sh-sh-dev** [comment]
> Nope, I don't have any. And it seems like Telegraf.js has removed the support for `apiRoot` and this means I cannot run the bot. expressionless
> 
> I've made some changes to the template in #3 but they're not tested...

`apiRoot` is still supported
Your problem reason is [this line of code](https://github.com/YouTwitFace/ThemerBot/blob/master/middleware/download.js#L4)
Links should be got with the `getFileLink` method

**Comment by heokhe** [comment]
Thanks to #4 I can run the bot now. I've made big changes to TGX template and also, I've added primary color support! 

The bot now accepts four colors instead of three. The fourth one is primary color (We need translations for `choose_color_4`). Telegram X supports primary colors well, but the template has problems yet.

I'm on a vacation now, but I'll push the changes in hours!

**Comment by vrumger** [comment]
@Hkh12 Did you also update the attheme template to use 4 colors?

**Comment by heokhe** [comment]
Not yet but I'll work on it later.
