### ISSUE TITLE
Error Invalid DSN

### ISSUE THREAD

**Issue by ghost** [ThemerBot/ThemerBot#22]
Hello I am wanting to mount the bot in aws amazon and I can not throw this error.
![image](https://user-images.githubusercontent.com/31140793/118749893-c9e57380-b834-11eb-87c4-66c9ad99e140.png)

**Comment by vrumger** [comment]
You need to either remove `SENTRY_DSN` from your `.env`, or put a valid token.

**Comment by ghost** [comment]
Sorry for the inconvenience, throw me this error now
![image](https://user-images.githubusercontent.com/31140793/118761866-92ce8c80-b84b-11eb-87c8-d859f371b9b7.png)

the token configures it well I don't know what it can be ,   Host Use ec2 from amazon

**Comment by vrumger** [comment]
You'll also need to remove `API_ROOT` from your `.env`.

**Comment by ghost** [comment]
this error because it can be?
![image](https://user-images.githubusercontent.com/31140793/118833093-8f60f280-b897-11eb-99bf-048ad832fcfd.png)

I'm getting closer to making it work

**Comment by vrumger** [comment]
Did you completely remove `API_ROOT` or just the value?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/31140793/118916899-2f556500-b906-11eb-922f-50482f0cd672.png)
![image](https://user-images.githubusercontent.com/31140793/118916952-4431f880-b906-11eb-801f-083a75d2ccff.png)

**Comment by vrumger** [comment]
Oh, you don't have to touch `env.js`, just your `.env`.

**Comment by vrumger** [comment]
And remove the `TELEGRAM:` part in your bot token.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/31140793/118917438-447ec380-b907-11eb-8844-2c4c479c309e.png)
sorry i didn't realize that.
But the strange thing is that it keeps throwing an error when starting. already install npm install todo.

**Comment by vrumger** [comment]
You need to uncomment `API_ROOT` in `env.js`, but remove it from your `.env`.

**Comment by ghost** [comment]
There I returned to default env.js and the error was changed, throw another one. 
The error seems to be because it does not install the "sharp" module in Ubuntu. 
![image](https://user-images.githubusercontent.com/31140793/118917921-4ac16f80-b908-11eb-918b-c04ea51dfe0d.png)
 use sudo npm install sharp and I threw that error

**Comment by ghost** [comment]
There I was able to repair, I am very grateful. sorry for the inconvenience

**Comment by vrumger** [comment]
👍
