### ISSUE TITLE
Does not respond

### ISSUE THREAD

**Issue by ghost** [ThemerBot/ThemerBot#23]
![image](https://user-images.githubusercontent.com/31140793/118921467-9bd46200-b90e-11eb-946e-cf5176073cf1.png)
Excuse me, why don't you answer?
It remains like this and nothing is placed.

In console it does not throw me any error.

**Comment by vrumger** [comment]
Did you make any modifications to the code?

**Comment by ghost** [comment]
not only the spanish translation download.
I try to reinstall from 0?

**Comment by vrumger** [comment]
Try setting the `DEBUG` environment variable to `themerbot:*`.

**Comment by ghost** [comment]
I don't really understand, I'm going to try to solve it. I did not sleep to solve and I can not know where I am wrong.
![image](https://user-images.githubusercontent.com/31140793/118981457-b92a2000-b950-11eb-91a8-39e5cdee6aa1.png)

the strangest thing is that it does not throw me any error.

**Comment by vrumger** [comment]
You can add `DEBUG=ThemerBot:*` to your `.env` file.

**Comment by ghost** [comment]
I use amazon, would I have to enable that port 6379?
![image](https://user-images.githubusercontent.com/31140793/118989703-a1569a00-b958-11eb-8572-d9b052ec09a7.png)

**Comment by vrumger** [comment]
You need Redis. There's a Docker Compose file if you want to use that.

**Comment by ghost** [comment]
There you can solve, thank you very much and I apologize for all the inconvenience.

I did not know that about redis

**Comment by vrumger** [comment]
Have you fixed the issue?

**Comment by ghost** [comment]
If yes, I did not have a database connected. that was the mistake.
