### ISSUE TITLE
Error windows 8

### ISSUE THREAD

**Issue by ghost** [ThemerBot/ThemerBot#24]
I wanted to ride the bot in windows 8 and this error happens me, try all change image_path in .env and nothing

I do not know what

![image](https://user-images.githubusercontent.com/31140793/119918015-08b6b000-bf3e-11eb-94cc-184684939b51.png)

![image](https://user-images.githubusercontent.com/31140793/119918105-3ac81200-bf3e-11eb-87b5-19aea3c41897.png)

**Comment by MorningSage** [comment]
This is due to the file name being used which contains characters that are invalid on in the Windows ecosystem.

#25 should fix it at least partially if not completely.  But, since I'm not familiar with the code base, I don't know if other parts rely on the name format or not.
